CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    score       INTEGER                                 NOT NULL,
    status      INTEGER                                 NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id)
);